using SFML.Graphics;
namespace FreeScape.Engine.Render.Utilities
{
    public static class CustomColors
    {
        public static Color maroon { get { return new Color(128, 0, 0); } }
        public static Color darkred { get { return new Color(139, 0, 0); } }
        public static Color brown { get { return new Color(165, 42, 42); } }
        public static Color firebrick { get { return new Color(178, 34, 34); } }
        public static Color crimson { get { return new Color(220, 20, 60); } }
        public static Color red { get { return new Color(255, 0, 0); } }
        public static Color tomato { get { return new Color(255, 99, 71); } }
        public static Color coral { get { return new Color(255, 127, 80); } }
        public static Color indianred { get { return new Color(205, 92, 92); } }
        public static Color lightcoral { get { return new Color(240, 128, 128); } }
        public static Color darksalmon { get { return new Color(233, 150, 122); } }
        public static Color salmon { get { return new Color(250, 128, 114); } }
        public static Color lightsalmon { get { return new Color(255, 160, 122); } }
        public static Color orangered { get { return new Color(255, 69, 0); } }
        public static Color darkorange { get { return new Color(255, 140, 0); } }
        public static Color orange { get { return new Color(255, 165, 0); } }
        public static Color gold { get { return new Color(255, 215, 0); } }
        public static Color darkgoldenrod { get { return new Color(184, 134, 11); } }
        public static Color goldenrod { get { return new Color(218, 165, 32); } }
        public static Color palegoldenrod { get { return new Color(238, 232, 170); } }
        public static Color darkkhaki { get { return new Color(189, 183, 107); } }
        public static Color khaki { get { return new Color(240, 230, 140); } }
        public static Color olive { get { return new Color(128, 128, 0); } }
        public static Color yellow { get { return new Color(255, 255, 0); } }
        public static Color yellowgreen { get { return new Color(154, 205, 50); } }
        public static Color darkolivegreen { get { return new Color(85, 107, 47); } }
        public static Color olivedrab { get { return new Color(107, 142, 35); } }
        public static Color lawngreen { get { return new Color(124, 252, 0); } }
        public static Color chartreuse { get { return new Color(127, 255, 0); } }
        public static Color greenyellow { get { return new Color(173, 255, 47); } }
        public static Color darkgreen { get { return new Color(0, 100, 0); } }
        public static Color green { get { return new Color(0, 128, 0); } }
        public static Color forestgreen { get { return new Color(34, 139, 34); } }
        public static Color lime { get { return new Color(0, 255, 0); } }
        public static Color limegreen { get { return new Color(50, 205, 50); } }
        public static Color lightgreen { get { return new Color(144, 238, 144); } }
        public static Color palegreen { get { return new Color(152, 251, 152); } }
        public static Color darkseagreen { get { return new Color(143, 188, 143); } }
        public static Color mediumspringgreen { get { return new Color(0, 250, 154); } }
        public static Color springgreen { get { return new Color(0, 255, 127); } }
        public static Color seagreen { get { return new Color(46, 139, 87); } }
        public static Color mediumaquamarine { get { return new Color(102, 205, 170); } }
        public static Color mediumseagreen { get { return new Color(60, 179, 113); } }
        public static Color lightseagreen { get { return new Color(32, 178, 170); } }
        public static Color darkslategray { get { return new Color(47, 79, 79); } }
        public static Color teal { get { return new Color(0, 128, 128); } }
        public static Color darkcyan { get { return new Color(0, 139, 139); } }
        public static Color aqua { get { return new Color(0, 255, 255); } }
        public static Color cyan { get { return new Color(0, 255, 255); } }
        public static Color lightcyan { get { return new Color(224, 255, 255); } }
        public static Color darkturquoise { get { return new Color(0, 206, 209); } }
        public static Color turquoise { get { return new Color(64, 224, 208); } }
        public static Color mediumturquoise { get { return new Color(72, 209, 204); } }
        public static Color paleturquoise { get { return new Color(175, 238, 238); } }
        public static Color aquamarine { get { return new Color(127, 255, 212); } }
        public static Color powderblue { get { return new Color(176, 224, 230); } }
        public static Color cadetblue { get { return new Color(95, 158, 160); } }
        public static Color steelblue { get { return new Color(70, 130, 180); } }
        public static Color cornflowerblue { get { return new Color(100, 149, 237); } }
        public static Color deepskyblue { get { return new Color(0, 191, 255); } }
        public static Color dodgerblue { get { return new Color(30, 144, 255); } }
        public static Color lightblue { get { return new Color(173, 216, 230); } }
        public static Color skyblue { get { return new Color(135, 206, 235); } }
        public static Color lightskyblue { get { return new Color(135, 206, 250); } }
        public static Color midnightblue { get { return new Color(25, 25, 112); } }
        public static Color navy { get { return new Color(0, 0, 128); } }
        public static Color darkblue { get { return new Color(0, 0, 139); } }
        public static Color mediumblue { get { return new Color(0, 0, 205); } }
        public static Color blue { get { return new Color(0, 0, 255); } }
        public static Color royalblue { get { return new Color(65, 105, 225); } }
        public static Color blueviolet { get { return new Color(138, 43, 226); } }
        public static Color indigo { get { return new Color(75, 0, 130); } }
        public static Color darkslateblue { get { return new Color(72, 61, 139); } }
        public static Color slateblue { get { return new Color(106, 90, 205); } }
        public static Color mediumslateblue { get { return new Color(123, 104, 238); } }
        public static Color mediumpurple { get { return new Color(147, 112, 219); } }
        public static Color darkmagenta { get { return new Color(139, 0, 139); } }
        public static Color darkviolet { get { return new Color(148, 0, 211); } }
        public static Color darkorchid { get { return new Color(153, 50, 204); } }
        public static Color mediumorchid { get { return new Color(186, 85, 211); } }
        public static Color purple { get { return new Color(128, 0, 128); } }
        public static Color thistle { get { return new Color(216, 191, 216); } }
        public static Color plum { get { return new Color(221, 160, 221); } }
        public static Color violet { get { return new Color(238, 130, 238); } }
        public static Color magentafuchsia { get { return new Color(255, 0, 255); } }
        public static Color orchid { get { return new Color(218, 112, 214); } }
        public static Color mediumvioletred { get { return new Color(199, 21, 133); } }
        public static Color palevioletred { get { return new Color(219, 112, 147); } }
        public static Color deeppink { get { return new Color(255, 20, 147); } }
        public static Color hotpink { get { return new Color(255, 105, 180); } }
        public static Color lightpink { get { return new Color(255, 182, 193); } }
        public static Color pink { get { return new Color(255, 192, 203); } }
        public static Color antiquewhite { get { return new Color(250, 235, 215); } }
        public static Color beige { get { return new Color(245, 245, 220); } }
        public static Color bisque { get { return new Color(255, 228, 196); } }
        public static Color blanchedalmond { get { return new Color(255, 235, 205); } }
        public static Color wheat { get { return new Color(245, 222, 179); } }
        public static Color cornsilk { get { return new Color(255, 248, 220); } }
        public static Color lemonchiffon { get { return new Color(255, 250, 205); } }
        public static Color lightgoldenrodyellow { get { return new Color(250, 250, 210); } }
        public static Color lightyellow { get { return new Color(255, 255, 224); } }
        public static Color saddlebrown { get { return new Color(139, 69, 19); } }
        public static Color sienna { get { return new Color(160, 82, 45); } }
        public static Color chocolate { get { return new Color(210, 105, 30); } }
        public static Color peru { get { return new Color(205, 133, 63); } }
        public static Color sandybrown { get { return new Color(244, 164, 96); } }
        public static Color burlywood { get { return new Color(222, 184, 135); } }
        public static Color tan { get { return new Color(210, 180, 140); } }
        public static Color rosybrown { get { return new Color(188, 143, 143); } }
        public static Color moccasin { get { return new Color(255, 228, 181); } }
        public static Color navajowhite { get { return new Color(255, 222, 173); } }
        public static Color peachpuff { get { return new Color(255, 218, 185); } }
        public static Color mistyrose { get { return new Color(255, 228, 225); } }
        public static Color lavenderblush { get { return new Color(255, 240, 245); } }
        public static Color linen { get { return new Color(250, 240, 230); } }
        public static Color oldlace { get { return new Color(253, 245, 230); } }
        public static Color papayawhip { get { return new Color(255, 239, 213); } }
        public static Color seashell { get { return new Color(255, 245, 238); } }
        public static Color mintcream { get { return new Color(245, 255, 250); } }
        public static Color slategray { get { return new Color(112, 128, 144); } }
        public static Color lightslategray { get { return new Color(119, 136, 153); } }
        public static Color lightsteelblue { get { return new Color(176, 196, 222); } }
        public static Color lavender { get { return new Color(230, 230, 250); } }
        public static Color floralwhite { get { return new Color(255, 250, 240); } }
        public static Color aliceblue { get { return new Color(240, 248, 255); } }
        public static Color ghostwhite { get { return new Color(248, 248, 255); } }
        public static Color honeydew { get { return new Color(240, 255, 240); } }
        public static Color ivory { get { return new Color(255, 255, 240); } }
        public static Color azure { get { return new Color(240, 255, 255); } }
        public static Color snow { get { return new Color(255, 250, 250); } }
        public static Color black { get { return new Color(0, 0, 0); } }
        public static Color dimgray { get { return new Color(105, 105, 105); } }
        public static Color gray { get { return new Color(128, 128, 128); } }
        public static Color darkgray{get{return new Color(169,169,169);}}
        public static Color silver { get { return new Color(192, 192, 192); } }
        public static Color lightgray{ get{ return new Color(211, 211, 211); } }
        public static Color gainsboro { get { return new Color(220, 220, 220); } }
        public static Color whitesmoke { get { return new Color(245, 245, 245); } }
        public static Color white { get { return new Color(255, 255, 255); } }

    }
}
